### ISSUE TITLE
Make use of Strong-Frida

### ISSUE THREAD

**Issue by azrinyi** [ViRb3/magisk-frida#16]
In order to avoid Frida being detected by various applications it would be beneficial if the following could be integrated:
https://github.com/feicong/strong-frida

**Comment by ViRb3** [comment]
That's a very interesting project, thanks for linking it. I don't know why the build script is failing for you, I will have to look into it. I am a bit busy now, but I will try to incorporate the project you referenced in a Magisk module somehow.

**Comment by enovella** [comment]
In any case, I would create another module `magisk-strong-frida` to avoid more problems

**Comment by ViRb3** [comment]
I was more considering to release two zips every update, especially since the Magisk repo is discontinued and this will the the official module channel. Should be trivial. The link to strong Frida is dead btw.

**Comment by lindoalex577** [comment]
There's another repo that uses Actions to patch and compile "strong" Frida: https://github.com/hzzheyang/strongR-frida-android

**Comment by zixing131** [comment]
Here is another repo : https://github.com/zixing131/strongR-frida/releases/tag/15.1.17

**Comment by forty875** [comment]
Hello, this is not Magisk related, but how to get frida and frida-tools working with strongR-frida-android server versions on client side?
```
Traceback (most recent call last):
  File "xxxxxxx.py", line xxx, in <module>
    pid = device.spawn(["xxxxxxxxxxxx"])
  File "C:\Python37\lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
  File "C:\Python37\lib\site-packages\frida\core.py", line 968, in spawn
    return self._impl.spawn(program, **kwargs)
frida.InvalidArgumentError: undefined symbol: main`
```

**Comment by h3x4n1um** [comment]
> 

I also had the same issue but I couldn't find solution for it :(

**Comment by MicroCBer** [comment]
> There's another repo that uses Actions to patch and compile "strong" Frida: [hzzheyang/strongR-frida-android](https://github.com/hzzheyang/strongR-frida-android)

I've created a fork for it.  
https://github.com/MicroCBer/magisk-strongR-frida

**Comment by devnoname120** [comment]
Here is yet another one: https://github.com/FriRebuild/magisk-strongR-frida

**Comment by devnoname120** [comment]
@ViRb3 FYI https://github.com/Magisk-Modules-Alt-Repo

**Comment by CyberillcButSmarter** [comment]
Anything new? It still gets detected by NHN appguard

**Comment by diogosilvan** [comment]
Yes, same problem here. Frida running in the background is instantly detected.
