### ISSUE TITLE
Magisk-Frida Conflict with Objection

### ISSUE THREAD

**Issue by soldiweb** [ViRb3/magisk-frida#27]
I was testing objection (https://github.com/sensepost/objection) with Frida today and worked fine using the non-magisk version of Frida but when I installed this version and tried objection I got this error:

`com.doodle.turboracing3d on (realme: 12) [usb] # frida
An unexpected internal exception has occurred. If this looks like a code related error, please file a bug report!
'filename'

Python stack trace: Traceback (most recent call last):
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\console\repl.py", line 371, in start_repl
    self.run_command(document)
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\console\repl.py", line 185, in run_command
    exec_method(arguments)
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python310\lib\site-packages\objection\commands\frida_commands.py", line 38, in frida_environment
    ('Script Filename', frida_env['filename']),
KeyError: 'filename'`

**Comment by ViRb3** [comment]
Hmm, I don't see how this would be a Magisk-Frida issue. Are you sure you were running the exact same version of Frida manually and then in Magisk-Frida? Was your Objection updated? Can you please re-test with the latest Frida version as of now (15.2.2)?

**Comment by ViRb3** [comment]
Closing, assuming fixed.
