### ISSUE TITLE
Issue with Zygisk

### ISSUE THREAD

**Issue by TA2k** [ViRb3/magisk-frida#30]
I use Magisk-Delta 25.2-delta6 with Zygisk enabled this cause no app is starting after activating Magisk-frida. After disabling Zygisk it is working again

**Comment by ViRb3** [comment]
Sounds like a clash between Magisk-Delta, Zygisk, and magisk-frida. Have you tried with regular Magisk? Does original Frida without this module work?

**Comment by cryptoexpertssss** [comment]
It is working with Riru but not Zygisk

**Comment by 4val0v** [comment]
I have a similar problem with enabled zygisk :(
BTW, I don't think that this issue relates to this module, because [frida-server](https://github.com/frida/frida/releases/tag/16.0.8) from the frida repository has the same behavior as described below by using this module

Pixel 2XL - Android 11 / Magisk 25.2 [(topjohnwu)](https://github.com/topjohnwu/Magisk)
Just a few seconds after booting up, the phone screen freezes and stops responding to touch
```
.........
                 Magisk  I  * Running module post-fs-data scripts
                         I  * Loading modules
                         I  magisk-frida: loading mount files
                         I  hosts: loading mount files
.........
                 Magisk  I  ** late_start service mode running
                         I  * Running service.d scripts
                         I  * Running module service scripts
                         I  magisk-frida: exec [service.sh]
.........
ceStorageMonitorService  W  java.io.IOException: Failed to free 1048576000 on storage device at /data
                         W      at com.android.server.pm.PackageManagerService.freeStorage(PackageManagerService.java:5129)
                         W      at com.android.server.storage.DeviceStorageMonitorService.check(DeviceStorageMonitorService.java:193)
                         W      at com.android.server.storage.DeviceStorageMonitorService.access$100(DeviceStorageMonitorService.java:72)
                         W      at com.android.server.storage.DeviceStorageMonitorService$1.handleMessage(DeviceStorageMonitorService.java:257)
                         W      at android.os.Handler.dispatchMessage(Handler.java:106)
                         W      at android.os.Looper.loop(Looper.java:223)
                         W      at android.os.HandlerThread.run(HandlerThread.java:67)
           crash_dump64  W  failed to attach to thread 1458, already traced by 4284 (frida-server)
                         E  failed to interrupt 1458 to detach: No such process
                         W  failed to ptrace interrupt thread 1458: No such process
                         W  failed to attach to thread 1460, already traced by 4284 (frida-server)
                         E  failed to interrupt 1460 to detach: No such process
                         W  failed to ptrace interrupt thread 1460: No such process
                         W  failed to attach to thread 1461, already traced by 4284 (frida-server)
                         E  failed to interrupt 1461 to detach: No such process
                         W  failed to ptrace interrupt thread 1461: No such process
                         W  failed to attach to thread 1468, already traced by 4284 (frida-server)
                         E  failed to interrupt 1468 to detach: No such process
                         W  failed to ptrace interrupt thread 1468: No such process
                         W  failed to attach to thread 1469, already traced by 4284 (frida-server)
                         E  failed to interrupt 1469 to detach: No such process
                         W  failed to ptrace interrupt thread 1469: No such process
                         W  failed to attach to thread 1470, already traced by 4284 (frida-server)
                         E  failed to interrupt 1470 to detach: No such process
                         W  failed to ptrace interrupt thread 1470: No such process
                         W  failed to attach to thread 1471, already traced by 4284 (frida-server)
                         E  failed to interrupt 1471 to detach: No such process
                         W  failed to ptrace interrupt thread 1471: No such process
                         W  failed to attach to thread 1651, already traced by 4284 (frida-server)
                         E  failed to interrupt 1651 to detach: No such process
                         W  failed to ptrace interrupt thread 1651: No such process
                         W  failed to attach to thread 1659, already traced by 4284 (frida-server)
                         E  failed to interrupt 1659 to detach: No such process
                         W  failed to ptrace interrupt thread 1659: No such process
.........
```
A135F - Android 12 / Magisk-Delta 25.2 [(5dfdfddd-delta)](https://github.com/HuskyDG/magisk-files/blob/main/note.md)
After booting up any application can't be started, even the widgets don't load, then the phone falls to the boot screen
```text
.........
                 Magisk  I  Magisk 5dfdfddd-delta(25206) daemon started
                         I  * Device API level: 31
                         I  * CPU ABI 32-bit: armeabi-v7a,armeabi
                         I  ** post-fs-data mode running
                         I  * Unlock device blocks
                         I  * Mount mirrors
                         I  PATH=[/product/bin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/system_ext/bin:/system/bin:/system/xbin:/odm/bin:/vendor/bin:/vendor/xbin]
                         I  * Initializing Magisk environment
                         I  * Running post-fs-data.d scripts
                         I  Upgrade / New module: magisk-frida
                         I  * Running module post-fs-data scripts
                         I  * Loading modules
                         I  magisk-frida: loading mount files
                  audit  E  type=1400 audit(1676053412.811:62): avc:  denied  { transition } for  pid=529 comm="init" path="/system/bin/sh" dev="dm-0" ino=1210 scontext=u:r:init:s0 tcontext=u:r:su:s0 tcla
                            ss=process permissive=0 SEPF_SM-A135F_12_0001 audit_filtered
                         E  type=1300 audit(1676053412.811:62): arch=40000028 syscall=11 per=8 success=yes exit=4294967283 a0=f734ca10 a1=f734c620 a2=f76b4fa0 a3=10 items=1 ppid=1 pid=529 auid=4294967295 
                            uid=1000 gid=1000 euid=1000 suid=1000 fsuid=1000 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=4294967295 comm="init" exe="/system/bin/init" subj=u:r:init:s0 key=(null)
                         E  type=1302 audit(1676053412.811:62): item=0 name="/system/bin/sh" inode=1210 dev=fd:00 mode=0100755 ouid=0 ogid=2000 rdev=00:00 obj=u:object_r:shell_exec:s0 nametype=NORMAL cap_
                            fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
                         E  type=1327 audit(1676053412.811:62): proctitle=2F73797374656D2F62696E2F696E6974007365636F6E645F7374616765
                         E  type=1400 audit(1676053412.835:63): avc:  denied  { create } for  pid=279 comm="init" name="exynos" scontext=u:r:vendor_init:s0 tcontext=u:object_r:system_data_file:s0 tclass=d
                            ir permissive=0 SEPF_SM-A135F_12_0001 audit_filtered
                         E  type=1300 audit(1676053412.835:63): arch=40000028 syscall=323 per=8 success=yes exit=4294967283 a0=ffffff9c a1=f7ac94a0 a2=1f9 a3=3 items=2 ppid=1 pid=279 auid=4294967295 uid=0
                             gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="init" exe="/system/bin/init" subj=u:r:vendor_init:s0 key=(null)
                         E  type=1302 audit(1676053412.835:63): item=0 name="/data/" inode=3 dev=fd:04 mode=040771 ouid=1000 ogid=1000 rdev=00:00 obj=u:object_r:system_data_root_file:s0 nametype=PARENT ca
                            p_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
                         E  type=1302 audit(1676053412.835:63): item=1 name="/data/exynos" nametype=CREATE cap_fp=0000000000000000 cap_fi=0000000000000000 cap_fe=0 cap_fver=0
                         E  type=1327 audit(1676053412.835:63): proctitle=2F73797374656D2F62696E2F696E697400737562636F6E7465787400753A723A76656E646F725F696E69743A7330003135
             CASS_DEBUG  I  Start Service... CASS v1.6.5
.........
                 Magisk  I  * Running module service scripts
                         I  magisk-frida: exec [service.sh]
.........
         PackageManager  I  Adding preference: com.google.android.apps.messaging/.ui.conversation.LaunchConversationActivity
                         I  Sets:
                         I  , uid: 1001, pid: 1259
                         I  Removing preference<replace>: com.google.android.apps.messaging/.ui.conversation.LaunchConversationActivity
                         I  Sets:
                         I    com.google.android.apps.messaging/.ui.conversation.LaunchConversationActivity
                         I    com.samsung.android.messaging/.ui.view.main.WithActivity
                         I    com.samsung.android.messaging/.ui.ComposeMessageMms, uid: 1001, pid: 1259
                         I  Adding preference: com.google.android.apps.messaging/.ui.conversation.LaunchConversationActivity
                         I  Sets:
                         I  , uid: 1001, pid: 1259
                  audit  E  type=1403 audit(1676053446.451:171): auid=4294967295 ses=4294967295 lsm=selinux res=1
                         E  type=1300 audit(1676053446.451:171): arch=40000028 syscall=4 per=8 success=yes exit=1855636 a0=3 a1=e7bd0780 a2=1c5094 a3=0 items=0 ppid=753 pid=2858 auid=4294967295 uid=0 gid=
                            0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="frida-server" exe="/system/bin/frida-server" subj=u:r:magisk:s0 key=(null)
                         E  type=1327 audit(1676053446.451:171): proctitle="frida-server"
           AudioFlinger  W  write blocked for 450 msecs, 1 delayed writes, thread 29
                         D  mixer(0xe62dc940) Spend too much time to write: delta 450(effect 0, stage 0)
                SELinux  I  SELinux: Loaded service_contexts from:
                         I      /system/etc/selinux/plat_service_contexts
                         I      /system_ext/etc/selinux/system_ext_service_contexts
                         I      /vendor/etc/selinux/vendor_service_contexts
                  audit  E  avc:  received policyload notice (seqno=2)
.........
        ActivityManager  E  ANR in com.sec.modem.settings
                         E  PID: 0
                         E  Reason: Broadcast of Intent { act=android.intent.action.SIM_STATE_CHANGED flg=0x15000010 (has extras) }
                         E  Frozen: false
                         E  Load: 0.0 / 0.0 / 0.0
                         E  ------ Current CPU Core Info ------
                         E  - offline :
                         E  - online : 0-7
                         E  - AP Temp = 329
                         E                               0           1           2           3           4           5           6           7
                         E  ------------------------------------------------------------------------------------------------------------------
                         E  scaling_cur_freq       2002000     2002000     2002000     2002000     2002000     2002000     2002000     2002000
                         E  scaling_governor   energy_step energy_step energy_step energy_step energy_step energy_step energy_step energy_step
                         E  scaling_max_freq       2002000     2002000     2002000     2002000     2002000     2002000     2002000     2002000
                         E  ------------------------------------------------------------------------------------------------------------------
                         E  ----- Output from /proc/pressure/memory -----
                         E  some avg10=1.05 avg60=0.39 avg300=0.09 total=304313
                         E  full avg10=0.62 avg60=0.22 avg300=0.05 total=208456
                         E  ----- End output from /proc/pressure/memory -----
                         E  CPU usage from 15980ms to 0ms ago (2023-02-10 20:24:03.157 to 2023-02-10 20:24:19.136):
                         E    69% 942/system_server: 50% user + 19% kernel / faults: 64423 minor 1142 major
                         .........
                         E    0% 26/migration/2: 0% user + 0% kernel
                         E    0% 27/ksoftirqd/2: 0% user + 0% kernel
                         E    0% 39/ksoftirqd/4: 0% user + 0% kernel
                         E    0% 43/tz_worker_threa: 0% user + 0% kernel
                         E    0% 44/migration/5: 0% user + 0% kernel
                         E    0% 45/ksoftirqd/5: 0% user + 0% kernel
                         E    0% 49/tz_worker_threa: 0% user + 0% kernel
                         E    0% 55/tz_worker_threa: 0% user + 0% kernel
                         E    0% 157/kworker/3:1-mm_percpu_wq: 0% user + 0% kernel
                         E    0% 158/kworker/5:1-pm: 0% user + 0% kernel
                         E    0% 160/kworker/6:1-mm_percpu_wq: 0% user + 0% kernel
                         E    0% 196/irq/140-11a0000: 0% user + 0% kernel
                         E    0% 216/kworker/4:2-cgroup_destroy: 0% user + 0% kernel
                         E    0% 225/kworker/2:4-events: 0% user + 0% kernel
                         E    0% 262/f2fs_discard-25: 0% user + 0% kernel
                         E    0% 264/f2fs_discard-25: 0% user + 0% kernel
                         E    0% 266/f2fs_discard-25: 0% user + 0% kernel
                         E    0% 268/f2fs_discard-25: 0% user + 0% kernel
                         E    0% 282/ueventd: 0% user + 0% kernel / faults: 57 minor 251 major
                         .........
                         E    0% 1393/webview_zygote: 0% user + 0% kernel / faults: 180 minor 7 major
                         E    0% 1956/com.google.android.cellbroadcastreceiver: 0% user + 0% kernel / faults: 45 minor
                         E    0% 2331/com.sec.location.nsflp2: 0% user + 0% kernel / faults: 73 minor
                         E    0% 2372/rdxd: 0% user + 0% kernel
                         E   +0% 2837/kbase_event: 0% user + 0% kernel
                         E   +0% 2858/frida-server: 0% user + 0% kernel
                         E   +0% 2859/roid.honeyboard: 0% user + 0% kernel
                         E   +0% 2879/kworker/u16:4-events_unbound: 0% user + 0% kernel
                         E   +0% 2882/com.google.android.permissioncontroller: 0% user + 0% kernel
                         E   +0% 2883/kworker/u16:5-events_unbound: 0% user + 0% kernel
                         E   +0% 2896/logcat: 0% user + 0% kernel
                         E   +0% 2906/logcat: 0% user + 0% kernel
                         E   +0% 2956/com.google.android.providers.media.module: 0% user + 0% kernel
                         E   +0% 2962/com.google.process.gservices: 0% user + 0% kernel
                         E   +0% 3093/kbase_event: 0% user + 0% kernel
                         E  38% TOTAL: 22% user + 14% kernel + 1.2% iowait + 0.2% softirq
                         E  CPU usage from 55281ms to 55281ms ago (1970-01-01 03:00:00.000 to 1970-01-01 03:00:00.000) with 0% awake:
                         E  0% TOTAL: 0% user + 0% kernel
.........
               Watchdog  W  !@*** WAITED_HALF
                         W  Load: 10.08 / 3.29 / 1.16
                         W  ------ Current CPU Core Info ------
                         W  - offline :
                         W  - online : 0-7
                         W  - AP Temp = 313
                         W                               0           1           2           3           4           5           6           7
                         W  ------------------------------------------------------------------------------------------------------------------
                         W  scaling_cur_freq       1846000     1846000     1846000     1846000      546000      546000      546000      546000
                         W  scaling_governor   energy_step energy_step energy_step energy_step energy_step energy_step energy_step energy_step
                         W  scaling_max_freq       2002000     2002000     2002000     2002000     2002000     2002000     2002000     2002000
                         W  ------------------------------------------------------------------------------------------------------------------
                         W  CPU usage from 60137ms to 0ms ago (2023-02-10 20:23:40.322 to 2023-02-10 20:24:40.459):
                         W    90% 942/system_server: 70% user + 20% kernel / faults: 405594 minor 3646 major
                         W    7.7% 631/surfaceflinger: 5.5% user + 2.1% kernel / faults: 5820 minor 11 major
                         W    6.8% 678/installd: 3.8% user + 3% kernel / faults: 492 minor 1 major
                         W    3.6% 109/kswapd0: 0% user + 3.6% kernel
                         W    3.5% 317/logd: 1.3% user + 2.1% kernel / faults: 3514 minor 13 major
                         W    1.7% 614/audioserver: 0.9% user + 0.7% kernel / faults: 817 minor 30 major
                         W    1.5% 319/servicemanager: 0.7% user + 0.8% kernel / faults: 76 minor 26 major
                         W    1.4% 1/init: 0.5% user + 0.8% kernel / faults: 1458 minor 48 major
                         .........
                         W    0% 32/migration/3: 0% user + 0% kernel
                         W    0% 157/kworker/3:1-events: 0% user + 0% kernel
                         .........
                         W   +0% 1368/ip6tables-restore: 0% user + 0% kernel
                         W   +0% 1393/webview_zygote: 0% user + 0% kernel
                         .........
                         W   +0% 2686/com.sec.android.app.safetyassurance: 0% user + 0% kernel
                         W   +0% 2708/com.sec.android.app.soundalive: 0% user + 0% kernel
                         W   +0% 2735/com.sec.spp.push: 0% user + 0% kernel
                         W   +0% 2837/kbase_event: 0% user + 0% kernel
                         W   +0% 2858/frida-server: 0% user + 0% kernel
                         W   +0% 2859/roid.honeyboard: 0% user + 0% kernel
                         W   +0% 2879/kworker/u16:4-adb: 0% user + 0% kernel
                         W   +0% 2882/com.google.android.permissioncontroller: 0% user + 0% kernel
                         W   +0% 2883/kworker/u16:5-events_unbound: 0% user + 0% kernel
                         W   +0% 2896/logcat: 0% user + 0% kernel
                         W   +0% 2906/logcat: 0% user + 0% kernel
                         W   +0% 2956/com.google.android.providers.media.module: 0% user + 0% kernel
                         W   +0% 2962/com.google.process.gservices: 0% user + 0% kernel
                         W   +0% 3093/kbase_event: 0% user + 0% kernel
                         W  30% TOTAL: 20% user + 9.3% kernel + 0.7% iowait + 0.4% softirq
.........
           crash_dump32  F  crash_dump.cpp:536] failed to attach to thread 943, already traced by 2858 (frida-server)
.........
          system_server  I  libdebuggerd_client: done dumping process 559
             tombstoned  W  missing output fd
        ActivityManager  I  Collecting stacks for native pid 943
          system_server  I  libdebuggerd_client: started dumping process 943
             tombstoned  I  registered intercept for pid 943 and type kDebuggerdNativeBacktrace
                   libc  I  Requested dump for tid 943 (main)
           crash_dump32  F  crash_dump.cpp:536] failed to attach to thread 943, already traced by 2858 (frida-server)
             tombstoned  I  received crash request for pid 943
                         I  found registered intercept of type kDebuggerdNativeBacktrace for requested type kDebuggerdAnyIntercept
                         I  found intercept fd 512 for pid 943 and type kDebuggerdNativeBacktrace
                         W  crash socket received short read of length 0 (expected 12)
          system_server  I  libdebuggerd_client: done dumping process 943
                   libc  F  crash_dump helper failed to exec, or was killed
```

**Comment by ViRb3** [comment]
Thanks for confirming that this is not a problem with the module. Closing.
